carrieayu/bop

client/src/assets/scss/dropDown.scss
client/src/assets/scss/main.scss
client/src/components/DropDown/DropDown.tsx

Reusable Dropdown

---

client/src/assets/scss/footer.scss
client/src/assets/scss/main.scss
client/src/components/Footer/FooterComponent.tsx

Implemented footer component

---

client/src/assets/scss/header.scss
client/src/assets/scss/main.scss
client/src/components/header/header.tsx
client/src/pages/login/login.tsx

reuseable header component

---

client/src/assets/scss/main.scss
client/src/assets/scss/pagination.scss
client/src/components/Pagination/Pagination.tsx

Done making pagination component

---

client/src/assets/scss/main.scss
client/src/assets/scss/table.scss
client/src/components/Table/table.component.tsx
client/src/components/Table/table.tsx
client/src/pages/login/login.tsx

reuseable table

---

backend/api/serializers.py
backend/api/views.py
client/src/pages/login/login.tsx

Authentication

---

client/src/assets/scss/dashboard.scss
client/src/assets/scss/graphDashboard.scss
client/src/assets/scss/main.scss
client/src/assets/scss/register.scss
client/src/components/Table/table.component.tsx
client/src/pages/dashboard/dashboard.tsx

Done creating dashboard layout

---

client/jest.config.js
client/package-lock.json
client/package.json
client/src/__test__/dashboard.test.tsx
client/src/__test__/login.test.tsx

Done testing UI of login and dashboard

---

backend/api/models.py
backend/api/serializers.py
backend/api/views.py
backend/backend/settings.py
backend/backend/urls.py
client/package-lock.json
client/src/api/api.ts
client/src/app/store.ts
client/src/constants.ts
client/src/entity/cardEntity.ts
client/src/entity/otherPlanningEntity.ts
client/src/pages/dashboard/dashboard.tsx
client/src/reducers/card/cardSlice.ts
client/src/routes/index.tsx
client/tsconfig.json

Function Redux Client App Cards Component

---

client/src/assets/scss/dashboard.scss
client/src/components/GraphDashboard/GraphDashboard.tsx
client/src/pages/dashboard/dashboard.tsx

Done changing the dashboard UI also the graph component UI

---

client/src/components/GraphDashboard/GraphDashboard.tsx
client/src/pages/dashboard/dashboard.tsx

Done fetching data for graph

---

client/src/assets/scss/main.scss
client/src/assets/scss/projectDataList.scss
client/src/components/Pagination/Pagination.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/routes/index.tsx

Done making Project Data List UI

---

client/src/pages/projectDataList/projectDataList.tsx

Done changing the data in the table of projectdatalist

---

backend/api/models.py

Added new fields on planningprojectdata

---

backend/api/models.py
backend/api/serializers.py
backend/api/views.py
client/src/assets/scss/main.scss
client/src/assets/scss/projectDataCreate.scss
client/src/pages/login/login.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx
client/src/routes/ProtectedRoutes.tsx
client/src/routes/index.tsx

Project Data Create Endpoint

---

backend/backend/urls.py

Done adding endpoint in urls

---

client/src/components/Table/table.component.tsx

update total ui design and code BE  revision for total value

---

client/src/app/store.ts
client/src/assets/scss/projectDataList.scss
client/src/components/Pagination/Pagination.tsx
client/src/pages/dashboard/dashboard.tsx
client/src/reducers/graph/graphSlice.ts

Done integrate data on graph

---

client/src/assets/scss/pagination.scss
client/src/assets/scss/projectDataList.scss
client/src/components/Pagination/Pagination.tsx
client/src/components/Table/table.component.tsx
client/src/pages/dashboard/dashboard.tsx
client/src/pages/projectDataList/projectDataList.tsx

updated selectable pagination

---

backend/api/views.py
backend/backend/settings.py
backend/backend/urls.py
client/src/pages/forgot/forgot.tsx
client/src/pages/resetPassword/resetPassword.tsx
client/src/routes/index.tsx

BACKEND endpoint for verify email and reset password

---

.gitignore
backend/api/models.py
backend/api/views.py
backend/requirements.txt
client/src/pages/dashboard/dashboard.tsx
client/src/pages/login/login.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx
client/src/routes/index.tsx

Minor updates

---

client/src/app/store.ts
client/src/pages/personnel_expenses/personnelExpenses.tsx
client/src/reducers/personnel/personnelExpensesSlice.tsx

fixing error messages

---

client/src/assets/scss/dashboard.scss
client/src/assets/scss/main.scss
client/src/assets/scss/pagination.scss
client/src/assets/scss/projectDataCreate.scss
client/src/assets/scss/projectDataList.scss
client/src/assets/scss/sidebar.scss
client/src/components/SideBar/Sidebar.tsx
client/src/pages/dashboard/dashboard.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx

Done modifying UI of three pages

---

backend/api/models.py
backend/api/serializers.py
backend/api/views.py
backend/backend/settings.py
backend/backend/urls.py
client/src/app/store.ts
client/src/assets/scss/main.scss
client/src/assets/scss/personnelExpenseCreate.scss
client/src/components/Button/Button.tsx
client/src/entity/personnelplanningEntity.ts
client/src/pages/login/login.tsx
client/src/pages/personnelCreate/personnelExpenseCreate.tsx
client/src/reducers/personnel/personnelPlanningSlice.ts
client/src/reducers/personnel/personnelSlice.ts
client/src/routes/index.tsx

PersonnelExpenseBackEnd

---

client/package-lock.json
client/package.json
client/src/components/GraphDashboard/GraphDashboard.tsx
client/src/pages/dashboard/dashboard.tsx
client/src/pages/login/login.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx

updated graph to fix error from live server

---

client/src/assets/scss/main.scss
client/src/assets/scss/pagination.scss
client/src/assets/scss/personnelExpenseCreate.scss
client/src/assets/scss/personnelExpensesList.scss
client/src/components/SideBar/Sidebar.tsx
client/src/pages/dashboard/dashboard.tsx
client/src/pages/personnelCreate/personnelExpenseCreate.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx

Done modifying web UI design

---

backend/api/models.py
backend/api/serializers.py
client/src/assets/scss/projectDataCreate.scss
client/src/components/Table/table.component.tsx
client/src/pages/dashboard/dashboard.tsx
client/src/pages/projectDataList/projectDataList.tsx

Project Create Endpoint modify

---

client/src/assets/scss/dashboard.scss
client/src/assets/scss/personnelExpenseCreate.scss
client/src/assets/scss/personnelExpensesList.scss
client/src/assets/scss/projectDataCreate.scss
client/src/assets/scss/projectDataList.scss
client/src/assets/scss/sidebar.scss
client/src/components/SideBar/Sidebar.tsx

Done modifying sidebar

---

client/src/assets/scss/dashboard.scss
client/src/assets/scss/personnelExpensesList.scss
client/src/assets/scss/projectDataCreate.scss
client/src/assets/scss/projectDataList.scss
client/src/pages/dashboard/dashboard.tsx
client/src/pages/personnelCreate/personnelExpenseCreate.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx

Modify UI for Headers

---

client/src/assets/scss/main.scss
client/src/assets/scss/notFound.scss
client/src/assets/scss/personnelExpensesList.scss
client/src/assets/scss/planning.scss
client/src/assets/scss/projectDataList.scss
client/src/components/SideBar/Sidebar.tsx
client/src/pages/dashboard/dashboard.tsx
client/src/pages/notFound/notFound.tsx
client/src/pages/personnelCreate/personnelExpenseCreate.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx
client/src/pages/planningUI/planning.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx
client/src/routes/index.tsx

Done modifying transitions

---

client/src/assets/scss/costofSalesRegistration.scss
client/src/assets/scss/main.scss
client/src/assets/scss/projectDataCreate.scss
client/src/pages/costofSalesList/costofSalesList.tsx
client/src/pages/costofSalesRegistration/costofSalesRegistration.tsx
client/src/pages/expensesList/expensesList.tsx
client/src/pages/expensesRegistration/expensesRegistration.tsx
client/src/routes/index.tsx

Done adding new screens

---

backend/api/models.py
backend/api/serializers.py

Done modifying models for database

---

client/src/assets/scss/personnelExpensesList.scss
client/src/assets/scss/projectDataCreate.scss
client/src/assets/scss/projectDataList.scss
client/src/pages/costofSalesRegistration/costofSalesRegistration.tsx
client/src/pages/expensesRegistration/expensesRegistration.tsx
client/src/pages/personnelCreate/personnelExpenseCreate.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx

Done adding dropdowns

---

client/src/assets/scss/dashboard.scss
client/src/assets/scss/projectDataCreate.scss
client/src/assets/scss/tablePlanning.scss
client/src/pages/dashboard/dashboard.tsx
client/src/pages/projectDataList/projectDataList.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx

Done chnaging UI of project data and dashboard

---

backend/api/serializers.py
backend/api/views.py
backend/backend/urls.py
client/src/assets/scss/tablePlanning.scss
client/src/components/Localhost/localhost.tsx
client/src/components/Table/tablePlanning.tsx

BE for implementing dynamic data on table

---

client/src/assets/scss/expensesRegistration.scss
client/src/assets/scss/main.scss
client/src/components/SideBar/Sidebar.tsx
client/src/pages/costofSalesList/costofSalesList.tsx
client/src/pages/expensesList/expensesList.tsx

Done adding new screens in sidebar

---

backend/api/serializers.py
client/src/components/Localhost/localhost.tsx
client/src/components/Table/tablePlanning.tsx

done applying dynamic data with formula

---

client/src/assets/scss/personnelExpensesList.scss
client/src/assets/scss/planning.scss
client/src/assets/scss/tablePlanning.scss
client/src/components/Localhost/localhost.tsx
client/src/components/Table/tablePlanning.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx

Done modifying the personnel table

---

client/src/pages/personnel_expenses/personnelExpenses.tsx

added dynamic values for personnel expenses list

---

client/src/assets/scss/dashboard.scss
client/src/assets/scss/personnelExpensesList.scss
client/src/assets/scss/planning.scss
client/src/assets/scss/projectDataList.scss
client/src/assets/scss/table.scss
client/src/assets/scss/tablePlanning.scss
client/src/pages/dashboard/dashboard.tsx
client/src/pages/projectDataList/projectDataList.tsx

Done modifying scroll bars in all screens

---

backend/api/views.py
backend/backend/urls.py
client/src/pages/expensesList/expensesList.tsx

dynamic value for expenses list

---

client/src/assets/scss/projectDataCreate.scss
client/src/pages/costofSalesRegistration/costofSalesRegistration.tsx
client/src/pages/expensesRegistration/expensesRegistration.tsx
client/src/pages/personnelCreate/personnelExpenseCreate.tsx
client/src/pages/projectDataRegistration/projectdataregistration.tsx

Done fixing month values in all registration screens

---

backend/api/views.py
backend/backend/urls.py
client/src/pages/costofSalesList/costofSalesList.tsx

display data in cost of sales list

---

backend/api/views.py
client/src/pages/costofSalesList/costofSalesList.tsx

code revisions

---

client/src/pages/costofSalesList/costofSalesList.tsx

modify the order of month in cost of sales

---

backend/api/models.py
backend/api/views.py
backend/backend/urls.py
client/src/pages/costofSalesRegistration/costofSalesRegistration.tsx

added save function for cos

---

backend/api/models.py
backend/api/views.py
backend/backend/urls.py
client/src/pages/expensesRegistration/expensesRegistration.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx

fix expenses registration function

---

client/src/assets/scss/login.scss
client/src/pages/login/login.tsx

done modify log in ui links

---

backend/api/models.py
backend/api/serializers.py
backend/api/views.py
client/src/pages/costofSalesRegistration/costofSalesRegistration.tsx

updated cos registration save function

---

client/src/assets/scss/dashboard.scss
client/src/assets/scss/planning.scss
client/src/assets/scss/tablePlanning.scss
client/src/components/Table/tablePlanning.tsx

Done fixing the planning tables width  also in dashboard

---

backend/api/views.py
client/src/components/Table/tablePlanning.tsx

Done modify endpoint that includes planning assign table

---

backend/api/views.py

modify planning views

---

backend/api/views.py
client/src/components/Table/table.component.tsx

updated dashboard

---

client/src/assets/scss/projectDataList.scss
client/src/pages/projectDataList/projectDataList.tsx

Done fixing table headers

---

backend/api/views.py
backend/backend/urls.py
client/src/pages/costofSalesRegistration/costofSalesRegistration.tsx
client/src/pages/expensesRegistration/expensesRegistration.tsx

backend for verifying duplicate month and update function

---

client/src/assets/scss/personnelExpensesList.scss
client/src/assets/scss/projectDataList.scss
client/src/translations/financial_words_en.json

Done fixing broken UI by translation

---

backend/api/views.py
client/src/components/Table/editTablePlanning.tsx
client/src/components/Table/tablePlanning.tsx

optimized update function for planning page

---

backend/api/models.py
backend/api/serializers.py
backend/api/urls.py
backend/api/views.py
backend/backend/urls.py

updated tables and column

---

client/src/assets/scss/Employees/EmployeesListAndEdit.scss
client/src/assets/scss/Employees/EmployeesRegistration.scss
client/src/assets/scss/main.scss
client/src/components/SideBar/Sidebar.tsx
client/src/pages/Employees/EmployeesListAndEdit.tsx
client/src/pages/Employees/EmployeesRegistration.tsx
client/src/routes/index.tsx
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

feat: created employees registration list and edit page (STATIC DATA)

---

client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

fixed translation general json files

---

backend/api/models.py
backend/api/serializers.py
backend/api/views.py
backend/backend/urls.py

fix conflicts and code revisions

---

client/src/pages/costofSalesList/costofSalesList.tsx
client/src/pages/expensesList/expensesList.tsx
client/src/pages/personnel_expenses/personnelExpenses.tsx
client/src/pages/projectDataList/projectDataList.tsx

fix: implement navigation for 新規登録 button

---

client/src/assets/scss/BusinessDivisions/BusinessDivisionsListAndEdit.scss
client/src/assets/scss/Clients/ClientsListAndEdit.scss
client/src/assets/scss/Employees/EmployeesListAndEdit.scss
client/src/assets/scss/Projects/ProjectsListAndEdit.scss
client/src/assets/scss/Users/UsersListAndEdit.scss
client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesList.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesList.tsx
client/src/pages/Employees/EmployeesListAndEdit.tsx
client/src/pages/Expenses/ExpensesList.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/Users/UsersListAndEdit.tsx

- Remove all paginator in all list screens

refactor: remove all paginator in all list screens

---

client/src/assets/scss/BusinessDivisions/BusinessDivisionsListAndEdit.scss
client/src/assets/scss/Clients/ClientsListAndEdit.scss
client/src/assets/scss/CostOfSales/CostOfSalesList.scss
client/src/assets/scss/Employees/EmployeesListAndEdit.scss
client/src/assets/scss/Expenses/ExpensesList.scss
client/src/assets/scss/Projects/ProjectsListAndEdit.scss
client/src/assets/scss/Users/UsersListAndEdit.scss
client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesList.tsx
client/src/pages/Employees/EmployeesListAndEdit.tsx
client/src/pages/Expenses/ExpensesList.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/Users/UsersListAndEdit.tsx

- Changed all horizantal to horizontal

refactor: change horizantal to horizontal

---

client/src/assets/scss/BusinessDivisions/BusinessDivisionsListAndEdit.scss
client/src/assets/scss/BusinessDivisions/BusinessDivisionsRegistration.scss
client/src/assets/scss/Clients/ClientsListAndEdit.scss
client/src/assets/scss/Clients/ClientsRegistration.scss
client/src/assets/scss/Components/Table.scss
client/src/assets/scss/Components/TablePlanning.scss
client/src/assets/scss/CostOfSales/CostOfSalesList.scss
client/src/assets/scss/CostOfSales/CostOfSalesRegistration.scss
client/src/assets/scss/Dashboard/Dashboard.scss
client/src/assets/scss/EmployeeExpenses/EmployeeExpensesList.scss
client/src/assets/scss/EmployeeExpenses/EmployeeExpensesRegistration.scss
client/src/assets/scss/Employees/EmployeesListAndEdit.scss
client/src/assets/scss/Employees/EmployeesRegistration.scss
client/src/assets/scss/Expenses/ExpensesList.scss
client/src/assets/scss/Expenses/ExpensesRegistration.scss
client/src/assets/scss/Planning/PlanningListAndEdit.scss
client/src/assets/scss/Projects/ProjectsListAndEdit.scss
client/src/assets/scss/Projects/ProjectsRegistration.scss
client/src/assets/scss/Users/UsersListAndEdit.scss

feature: added scrollbars

---

backend/api/models.py
backend/api/serializers.py
backend/api/urls.py
backend/api/views.py
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/Clients/ClientsRegistration.tsx
client/src/pages/Employees/EmployeesListAndEdit.tsx
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

implemented client CRUD

---

backend/api/models.py
backend/api/serializers.py
backend/api/views.py
backend/backend/urls.py
client/src/assets/scss/CostOfSales/CostOfSalesList.scss
client/src/assets/scss/CostOfSales/CostOfSalesRegistration.scss
client/src/components/AlertModal/AlertModal.tsx
client/src/components/Localhost/Localhost.tsx
client/src/pages/CostOfSales/CostOfSalesList.tsx
client/src/pages/CostOfSales/CostOfSalesRegistration.tsx
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

- Made the cost-of -sales list screen dynamic
- Fixed the cost-of-sales registration
- Added a new modal message for the cancel in delete modal message
- Added new kanji and english words in general_words json
---
- Need to migrate to apply changes of the backend

refactor: cost-of-sales screens frontend

---

client/src/assets/scss/Projects/ProjectsRegistration.scss
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/Projects/ProjectsRegistration.tsx
client/src/translations/financial_words_en.json
client/src/translations/financial_words_jp.json
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

fix translation and names

---

backend/backend/urls.py

fix duplicate import on url.api backend

---

backend/api/urls.py
backend/api/views.py
backend/backend/urls.py
client/src/pages/Employees/EmployeesListAndEdit.tsx

- [/ ] Feature addition
- [/ ] Bug fix
---
• I created a new endpoint for filter data in Edit mode

implemented edit, applied dependent business dropdown to company

---

backend/api/views.py
client/src/assets/scss/Employees/EmployeesRegistration.scss
client/src/pages/Employees/EmployeesRegistration.tsx

Origin/bug fix/bop 112 [company and business division dropdown fix]

---

backend/api/models.py
backend/api/views.py
client/src/assets/scss/EmployeeExpenses/EmployeeExpensesList.scss
client/src/assets/scss/EmployeeExpenses/EmployeeExpensesRegistration.scss
client/src/components/Localhost/Localhost.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesList.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx

---
- Please pull from develop then migrate

Feature/employee expenses/ticket#59

---

backend/api/views.py
client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesListAndEdit.tsx
client/src/pages/Expenses/ExpensesListAndEdit.tsx

fix updated_at when updating data

---

client/src/assets/scss/Components/CrudModal.scss
client/src/assets/scss/main.scss
client/src/components/AlertModal/AlertModal.tsx
client/src/components/CrudModal/CrudModal.tsx
client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
client/src/pages/BusinessDivisions/BusinessDivisionsRegistration.tsx
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/Clients/ClientsRegistration.tsx
client/src/pages/CostOfSales/CostOfSalesListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesRegistration.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesList.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
client/src/pages/Employees/EmployeesListAndEdit.tsx
client/src/pages/Employees/EmployeesRegistration.tsx
client/src/pages/Expenses/ExpensesListAndEdit.tsx
client/src/pages/Expenses/ExpensesRegistration.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/Projects/ProjectsRegistration.tsx
client/src/pages/Users/UsersListAndEdit.tsx
client/src/pages/Users/UsersRegistration.tsx
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

fix: change all alert messages to custom modal in all screens

---

client/src/assets/scss/BusinessDivisions/BusinessDivisionsListAndEdit.scss
client/src/assets/scss/Clients/ClientsListAndEdit.scss
client/src/assets/scss/CostOfSales/CostOfSalesListAndEdit.scss
client/src/assets/scss/Dashboard/Dashboard.scss
client/src/assets/scss/Employees/EmployeesListAndEdit.scss
client/src/assets/scss/Expenses/ExpensesListAndEdit.scss
client/src/assets/scss/Planning/PlanningListAndEdit.scss
client/src/assets/scss/Projects/ProjectsListAndEdit.scss
client/src/assets/scss/Users/UsersListAndEdit.scss
client/src/assets/scss/Users/UsersRegistration.scss
client/src/components/Table/TablePlanningA.tsx
client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesListAndEdit.tsx
client/src/pages/Employees/EmployeesListAndEdit.tsx
client/src/pages/Users/UsersListAndEdit.tsx

fix: UI issues

---

client/src/assets/scss/BusinessDivisions/BusinessDivisionsRegistration.scss
client/src/assets/scss/Clients/ClientsRegistration.scss
client/src/assets/scss/Components/ListButtons.scss
client/src/assets/scss/Components/RegistrationButtons.scss
client/src/assets/scss/Components/Sidebar.scss
client/src/assets/scss/CostOfSales/CostOfSalesRegistration.scss
client/src/assets/scss/EmployeeExpenses/EmployeeExpensesRegistration.scss
client/src/assets/scss/Employees/EmployeesRegistration.scss
client/src/assets/scss/Expenses/ExpensesRegistration.scss
client/src/assets/scss/Projects/ProjectsRegistration.scss
client/src/assets/scss/Users/UsersRegistration.scss
client/src/components/RegistrationButtons/RegistrationButtons.tsx
client/src/pages/BusinessDivisions/BusinessDivisionsRegistration.tsx
client/src/pages/Clients/ClientsRegistration.tsx
client/src/pages/CostOfSales/CostOfSalesRegistration.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
client/src/pages/Employees/EmployeesRegistration.tsx
client/src/pages/Expenses/ExpensesRegistration.tsx
client/src/pages/Projects/ProjectsRegistration.tsx
client/src/pages/Users/UsersRegistration.tsx
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

feat: added new button in all registrtaion for shortcut in List Screen

---

client/src/assets/scss/BusinessDivisions/BusinessDivisionsRegistration.scss
client/src/assets/scss/Components/ListButtons.scss
client/src/assets/scss/Dashboard/Dashboard.scss
client/src/assets/scss/Employees/EmployeesListAndEdit.scss
client/src/assets/scss/Projects/ProjectsListAndEdit.scss
client/src/assets/scss/Users/UsersRegistration.scss

fix: used media query for small laptops

---

client/src/components/Table/TablePlanningA.tsx

- [/ ] Bug fix
- [/ ] Refactoring
- [/ ] Documentation update
---

done fix planning screen

---

client/src/components/Table/TablePlanningA.tsx
client/src/pages/Dashboard/Dashboard.tsx
client/src/pages/Planning/PlanningListAndEdit.tsx

done implementing round up for thousand yen

---

backend/api/views.py
backend/backend/settings.py
client/src/reducers/table/tableSlice.ts

fix reset password and table slice

---

client/src/components/Localhost/Localhost.tsx
client/src/pages/Login/Login.tsx

Fixed Eye Icon & Password Visible Toggle on Login Screen

---

client/src/components/Localhost/Localhost.tsx

changed endpoints from local:127 to live:54

---

client/src/components/Localhost/Localhost.tsx

Changed Endpoint in local.tsx

---

backend/api/serializers.py
backend/api/urls.py
backend/api/views.py
backend/backend/urls.py
client/src/components/Table/TablePlanningA.tsx
client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
client/src/pages/BusinessDivisions/BusinessDivisionsRegistration.tsx
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/Clients/ClientsRegistration.tsx
client/src/pages/CostOfSales/CostOfSalesListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesRegistration.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesList.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
client/src/pages/Employees/EmployeesListAndEdit.tsx
client/src/pages/Employees/EmployeesRegistration.tsx
client/src/pages/Expenses/ExpensesListAndEdit.tsx
client/src/pages/Expenses/ExpensesRegistration.tsx
client/src/pages/ForgotPassword/ForgotPassword.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/ResetPassword/ResetPassword.tsx
client/src/pages/Users/UsersListAndEdit.tsx
client/src/pages/Users/UsersRegistration.tsx
client/src/reducers/businessdivisions/businessdivisionsSlice.ts
client/src/reducers/card/cardSlice.ts
client/src/reducers/client/clientSlice.ts
client/src/reducers/company/companySlice.ts
client/src/reducers/graph/graphSlice.ts
client/src/reducers/personnel/personnelPlanningSlice.ts
client/src/reducers/table/tableSlice.ts

Refactored Views, API  Urls.py, Paths , Serializers so that names follow same conventions

---

backend/api/models.py

updated model for projects (removed unique attribute)

---

client/src/toggleEndpoint.ts

Changed to live server endpoint

---

client/src/toggleEndpoint.ts

changed endpoint to local

---

client/src/toggleEndpoint.ts

changed endpoints

---

backend/api/views.py
backend/backend/urls.py
client/src/api/EmployeeExpensesResultEndpoint/FilterGetEmployeeExpenseResult.ts
client/src/pages/EmployeeExpensesResults/EmployeeExpenseResultsList.tsx
client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
client/src/translations/financial_words_en.json
client/src/translations/financial_words_jp.json
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json
client/src/translations/screenNames_words_en.json
client/src/translations/screenNames_words_jp.json

added overwrite function on project sales result page

---

client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesListAndEdit.tsx
client/src/pages/Expenses/ExpensesListAndEdit.tsx
client/src/pages/ExpensesResults/ExpensesResultsListAndEdit.tsx
client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/Users/UsersListAndEdit.tsx
client/src/translations/screenNames_words_en.json

Bug fixes/bop 156

---

client/src/toggleEndpoint.ts
client/webpack.config.js

Added thread loader to config file {test to fix live server issues}

---

client/src/toggleEndpoint.ts

Changed Endpoint to Live

---

client/package-lock.json
client/package.json
client/src/toggleEndpoint.ts

Installed Thread Loader Dependency & Changed Endpoint to Live

---

client/package-lock.json
client/package.json

uninstall previously added thread dependency

---

backend/api/serializers.py
backend/api/views.py
client/src/assets/scss/EmployeeExpenses/EmployeeExpensesList.scss
client/src/assets/scss/EmployeeExpensesResults/EmployeeExpensesResultsList.scss
client/src/assets/scss/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.scss
client/src/pages/Clients/ClientsListAndEdit.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesList.tsx
client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
client/src/pages/EmployeeExpensesResults/EmployeeExpenseResultsList.tsx
client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx

[https://dattjapan.backlog.com/view/BOP_MANAGEMENT_SYSTEM-171](https://dattjapan.backlog.com/view/BOP_MANAGEMENT_SYSTEM-171)

fixed project name , month duplicates and dropdown bug in year

---

client/src/assets/scss/Results/ResultsListAndEdit.scss
client/src/components/TableResults/EditTableResults.tsx
client/src/components/TableResults/TableResultA.tsx
client/src/components/TableResults/TableResultB.tsx
client/src/pages/Results/ResultsListAndEdit.tsx
client/src/translations/general_words_en.json
client/src/translations/general_words_jp.json

fix header translation

---

client/src/pages/Employees/EmployeesListAndEdit.tsx

- 1. 従業員一覧で編集モードONにしたところ記載者が「1」になりました。
- 2. 従業員一覧で一覧モードユーザIDではなく,名と姓に変更する (受注事業部一覧と同じ)

タスク168 Employees List & Edit / 従業員　一覧・編集　記載者修正

---

client/src/app/store.ts
client/src/entity/cosEntity.ts
client/src/pages/Dashboard/Dashboard.tsx
client/src/reducers/card/cardSlice.ts
client/src/reducers/costOfSale/costOfSaleSlice.ts

[https://dattjapan.backlog.com/view/BOP_MANAGEMENT_SYSTEM-152](https://dattjapan.backlog.com/view/BOP_MANAGEMENT_SYSTEM-152)
---

fix gross profit calculation

---

backend/api/models.py
client/src/assets/scss/CostOfSales/CostOfSalesListAndEdit.scss
client/src/assets/scss/Expenses/ExpensesListAndEdit.scss
client/src/components/Table/TablePlanningA.tsx
client/src/constants.ts
client/src/pages/CostOfSales/CostOfSalesListAndEdit.tsx
client/src/pages/CostOfSales/CostOfSalesRegistration.tsx
client/src/pages/Expenses/ExpensesListAndEdit.tsx
client/src/pages/Expenses/ExpensesRegistration.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/Projects/ProjectsRegistration.tsx
client/src/utils/helperFunctionsUtil.ts
client/src/utils/validationUtil.ts

- Had Issues with merging branch 174 due to develop updates.
- Created a new branch from most recent develop and re-added changes.

origin/fix/bop 174 B (NEW)

---

backend/api/models.py
client/src/pages/CostOfSalesResults/CostOfSalesResultsListAndEdit.tsx
client/src/pages/CostOfSalesResults/CostOfSalesResultsRegistration.tsx
client/src/pages/ExpensesResults/ExpensesResultsListAndEdit.tsx
client/src/pages/ExpensesResults/ExpensesResultsRegistration.tsx
client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/utils/helperFunctionsUtil.ts

Bug fix/186

---

client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
client/src/pages/Projects/ProjectsListAndEdit.tsx
client/src/pages/Users/UsersListAndEdit.tsx

English
Project List not displaying updated data until screen refresh.　案件一覧・編集
Project Results List not displaying updated data until screen refresh. 案件実績一覧・編集
User List not displaying updated data until screen refresh. 案件実績一覧・編集
日本語
画面を更新するまで(refresh)、案件編集画面に変更された情報は一覧画面に反映していない
画面を更新するまで(refresh)、案件実績編集画面に変更された情報は一覧画面に反映していない
画面を更新するまで(refresh)、ユーザー編集画面に変更された情報は一覧画面に反映していない

WIP: Origin/fix/bop 190

---

client/src/components/Table/EditTablePlanning.tsx
client/src/components/Table/TablePlanningA.tsx
client/src/components/TableResults/EditTableResults.tsx
client/src/components/TableResults/TableResultA.tsx
client/src/components/TableResults/TableResultB.tsx
client/src/pages/Results/ResultsListAndEdit.tsx

This bug may possibly have been introduced after values were changed from INT to DECIMAL    
Decimal defaults to string automatically so instead of values being added they are creating one long string.
---

Ticket 194: Strings converted to Numbers (calculations & display)

---

backend/api/views.py
client/src/components/Table/EditTablePlanning.tsx
client/src/components/Table/TablePlanningA.tsx
client/src/components/TableResults/EditTableResults.tsx
client/src/components/TableResults/TableResultA.tsx
client/src/utils/helperFunctionsUtil.ts

BOP TICKET 
https://dattjapan.backlog.com/view/BOP_MANAGEMENT_SYSTEM-195
---

Bug fix/195

---

backend/api/models.py

- デフォルトの年を'2001'から'2024'に変更しました。
- デフォルトの月と選択肢を変更しました：
→ 01（INT）から'1'（STRING）へ変更
→ 一桁の数字の先頭にある0を削除しました。
---

updated model defaults

---

client/src/toggleEndpoint.ts

Develop toggle endpoint to live server

---

client/src/toggleEndpoint.ts

toggled back to local

---

client/src/toggleEndpoint.ts

toggleEndpoint edit
